root = "."
tmp_dir = "tmp"

[build]
  full_bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "postgres_data"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  poll = true
  poll_interval = 500

[screen]
  clear_on_rebuild = true